In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris

In [3]:
# Generate some sample data
np.random.seed(0)
X = np.random.rand(100, 1)  # Input feature
y = 2 * X + 1 + 0.1 * np.random.randn(100, 1)  # True labels with some noise

In [5]:
model = Sequential()
model.add(Dense(1, input_shape=(1,)))  # Single dense layer (linear regression)

C:\Users\MANI BUTWALL\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
# Compile the model
model.compile(optimizer='sgd', loss='mean_squared_error')

In [34]:
# Train the model
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0104
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0093
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0097
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0098 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0099
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0098 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0096
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0094
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0113
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0095
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0096
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0100
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0114
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0101
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0096
Epoch 16/100
4/4 

In [11]:
# Print the learned weights
print("Learned weights: ", model.layers[0].get_weights())

Learned weights:  [array([[1.7502308]], dtype=float32), array([1.142068], dtype=float32)]


In [13]:
new_X_reg = np.array([[0.6], [0.8]])
predictions_reg = model.predict(new_X_reg)
print("Regression predictions:")
print(predictions_reg)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
Regression predictions:
[[2.1922064]
 [2.5422525]]


In [15]:
# Build a deep neural network model
model = Sequential()
model.add(Dense(32, input_shape=(1,), activation='relu'))  # Hidden layer 1
model.add(Dense(16, activation='relu'))                   # Hidden layer 2
model.add(Dense(1))                                       # Output layer


In [17]:
# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

In [19]:
# Train the model
model.fit(X, y, epochs=100, verbose=0)

In [21]:
new_X_reg = np.array([[0.6], [0.8]])
predictions_reg = model.predict(new_X_reg)
print("Regression predictions:")
print(predictions_reg)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step
Regression predictions:
[[2.2195983]
 [2.6054153]]


In [23]:
# Build a deep neural network model
model = Sequential()
model.add(Dense(32, input_shape=(1,), activation='relu'))  # Hidden layer 1
model.add(Dense(16, activation='relu'))                   # Hidden layer 2
model.add(Dense(1)) 

In [25]:
# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X, y, epochs=100, verbose=0)


In [27]:
# Make predictions
new_X_reg = np.array([[0.6], [0.8]])
predictions_reg = model.predict(new_X_reg)
print("Regression predictions:")
print(predictions_reg)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step
Regression predictions:
[[2.2221699]
 [2.6317077]]
